### PR TITLE
Added Dev build info

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**
Thought it should at least be pointed out.

### CODE REVIEW

**Comment by ItsPugle** [comment]
Hmm - Maybe we don't need a whole section for it? Maybe we should change Discord Canary to Discord Builds and include them all? 

Since Discord Developer Build isn't public, per se, I don't wanna really share it too much in fear of damage.

**Comment by gidoBOSSftw5731** [comment]
That seems like it may be a better idea.

**Comment by ItsPugle** [comment]
I'm about to go to sleep, but if you want to change that on your fork so I can merge that in once I've decided on merging the reorganisation branch, that'd be good

**Comment by gidoBOSSftw5731** [comment]
As you said, its done.
Also sleep well

**Comment by ItsPugle** [comment]
Done done!

**Pull request merged**
