### PR TITLE
Reorganising the directory system

### PR DESCRIPTION
**Pull request by ItsPugle**
Thoughts?

### CODE REVIEW

**Comment by Phineas** [comment]
lgtm

**Comment by ItsPugle** [comment]
You're more experienced in everything compared to me, @Phineas, so any suggestions about anything?

**Comment by Phineas** [comment]
@ItsPugle Looks fine to me, I might make a pr later on

**Comment by ItsPugle** [comment]
Sweet - If there are no objections, I'll merge it in.

**Pull request merged**
